### Create Item (Command Service)
POST http://localhost:3000/api/command/items
Content-Type: application/json

{
  "name": "Camping Tent",
  "price": 99.99
}

### Get Items (Query Service)
GET http://localhost:3000/api/query/items
kp